export const projects = [
  {
    title: 'Krypt App',
    description:"A Web 3.0 App where one can send ethereum coins securely ",
    image: '/images/Krypt-App.png',
    tags: [ 'React Js', 'Solidity', 'MetaMask', 'HardHat' ],
    source: 'https://printzonedigitalpartner.sltindustries.com/',
    visit: 'https://printzonedigitalpartner.sltindustries.com/',
    id: 1,
  },
  {
    title: 'Cryptoverse',
    description:"A Cryptocurrency App where all information regarding the Cryptocurrency such as News, Exchanges and Statistics is available",
    image: '/images/cryptoverse.jpeg',
    tags: [ 'React Js', ' Redux Toolkit', ' RapidAPI' ],
    source: 'https://cryptoverse-report.netlify.app/',
    visit: 'https://cryptoverse-report.netlify.app/',
    id: 2,
  },
  {
    title: 'AI News App',
    description:"A News App which can be read through AI, Alan AI will read out the news for you",
    image: '/images/AI News App.png',
    tags: [ 'React Js', 'Alan AI' ],
    source: 'https://ai-news-app.netlify.app/',
    visit: 'https://ai-news-app.netlify.app/',
    id: 3,
  },
  {
    title: 'Covid-19 Global Tracker',
    description: "Using React Js have developed global covid cases tracker, where one can track covid cases in each country ",
      image: '/images/globaltracker.png',
      tags: ['React', 'Material UI'],
    source: 'https://covid19globaltracker.herokuapp.com/',
    visit: 'https://covid19globaltracker.herokuapp.com/',
    id: 4,
  },
  // {
  //   title: 'SLT Industries',
  //   description:"Website & CRM for a service based company to automate invoices, Orders through CRM",
  //   image: '/images/slt-industries.png',
  //   tags: [ 'Codeingiter', 'Javascript'],
  //   source: 'https://printzonedigitalpartner.sltindustries.com/',
  //   visit: 'https://printzonedigitalpartner.sltindustries.com/',
  //   id: 3,
  // },
  // {
  //   title: 'WebRTC App',
  //   description: "This is a code repository for the corresponding YouTube video. In this tutorial, we're going to build and deploy a React Video Chat Application using WebRTC.",
  //     image: '/images/3.jpg',
  //     tags: ['React', 'WebRTC'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 2,
  // },
  // {
  //   title: 'Unichat',
  //   description: "This is a code repository for the corresponding video tutorial. In this video, we will create a full Realtime Chat Application",
  //   image: '/images/4.jpg',
  //   tags: ['React', 'ChatEngine', 'Firebase'],
  //   source: 'https://google.com',
  //   visit: 'https://google.com',
  //   id: 3,
  // },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey as Intern', },
  { year: 2018, text: 'Worked as Software Developer', },
  { year: 2020, text: 'Shared my projects with the world', },
  { year: 2021, text: 'Started my own platform', },
];